#pragma once


enum StringNames {


String_health,
String_healthregeneration,
String_armour,
String_strength,
String_criticalchance,
String_criticaldamage,
String_luck,
String_breakingspeed,
String_speed,
String_mana,
String_manaregeneration,
String_light,

String_levelup,
String_skill_armour_title,
String_skill_armour_description,
String_skill_breakingspeed_title,
String_skill_breakingspeed_description,
String_skill_criticalchance_title,
String_skill_criticalchance_description,
String_skill_criticaldamage_title,
String_skill_criticaldamage_description,
String_skill_health_title,
String_skill_health_description,
String_skill_healthregeneration_title,
String_skill_healthregeneration_description,
String_skill_luck_title,
String_skill_luck_description,
String_skill_magicpoint_title,
String_skill_magicpoint_description,
String_skill_mana_title,
String_skill_mana_description,
String_skill_manaregeneration_title,
String_skill_manaregeneration_description,
String_skill_recipe_title,
String_skill_recipe_description,
String_skill_speed_title,
String_skill_speed_description,
String_skill_strength_title,
String_skill_strength_description,

String_empty_1,
String_empty_2,
String_empty_3,
String_empty_4,

String_consumable,
String_duration,

String_of_armour,
String_of_breakingspeed,
String_of_strength,
String_of_health,
String_of_speed,
String_of_luck,
String_of_mana,
String_of_healthregeneration,
String_of_manaregeneration,
String_of_criticalchance,
String_of_criticaldamage,
String_of_light,

String_empty_5,
String_empty_6,
String_empty_7,

String_write_your_name,
String_nobody,
String_minutes,
String_no_highscore,
String_level_reached,
String_startclass,

String_miner,
String_miner_info,
String_builder,
String_builder_info,
String_warrior,
String_warrior_info,
String_mage,
String_mage_info,
String_cheater,

String_empty_8,
String_empty_9,

String_new_world,

String_empty_10,
String_empty_11,

String_spell_not_learne,
String_spell_on_highest_level,
String_spell_on_next_level,
String_damage,
String_manacosts,

String_fireball,
String_fireball_description,
String_iceball,
String_iceball_description,
String_frozen_time,
String_poisoncloud,
String_poisoncloud_description,
String_poison_level,
String_poison_duration,

String_empty_12,
String_empty_13,
String_empty_14,
String_empty_15,
String_empty_16,
String_empty_17,
String_empty_18,
String_empty_19,
String_empty_20,

String_heal,
String_heal_description,
String_healthpoints,
String_manashield,
String_manashield_description,

String_empty_21,
String_empty_22,
String_empty_23,
String_empty_24,
String_empty_25,
String_empty_26,
String_empty_27,
String_empty_28,
String_empty_29,
String_empty_30,
String_empty_31,
String_empty_32,
String_empty_33,

String_alchemy,
String_alchemy_description,
String_chance_for_higher_block,
String_chance_for_lower_block,
String_lightspell,
String_lightspell_description,
String_lightradius,
String_teleport,
String_teleport_description,
String_width,

String_empty_34,
String_empty_35,
String_empty_36,
String_empty_37,
String_empty_38,
String_empty_39,
String_empty_40,
String_empty_41,
String_empty_42,
String_empty_43,
String_empty_44,
String_empty_45,
String_empty_46,
String_empty_47,

String_inventory,
String_building,
String_attributes,
String_magic,

String_empty_48,

String_play,
String_options,
String_highscore,
String_quit,

String_load_game,
String_new_game,
String_multiplayer,

String_settings,
String_achievements,
String_upgrades,

String_return,

String_delete_highscore,
String_delete_game,
String_beamnumbers_off,
String_beamnumbers_on,
String_inventorynumbers_off,
String_inventorynumbers_on,
String_beautiful_lightrendering,
String_fast_lightrendering,

String_start_game,

String_small_world,
String_medium_world,
String_big_world,

String_continue,
String_save,

String_controls,
String_basics,
String_userinterface,
String_charactervalues,
String_inventory2,
String_building2,
String_magic2,

String_empty_49,
String_empty_50,
String_empty_51,

String_a_or_arrowkey,
String_walk_left,
String_d_or_arrowkey,
String_walk_right,
String_w_or_arrowkey,
String_jump,
String_s,
String_break_jump,
String_e,
String_open_close_inventory,
String_b,
String_open_close_buildingmenu,
String_c,
String_open_close_charactermenu,
String_,
String_open_close_magicmenu,
String_left_mouse_button,
String_actions_left_mouse_button,
String_right_mouse_button,
String_actions_right_mouse_button,
String_mousewheel,
String_actions_mousewheel,
String_one_to_zero,
String_actions_one_to_zero,
String_f6,
String_fastsaving,
String_f1,
String_open_close_helppage,
String_k,
String_open_close_minimap,

String_aim_of_game,
String_steps_to_aim,
String_first_step_to_aim,
String_second_step_to_aim,
String_third_step_to_aim,
String_fourth_step_to_aim1,
String_fourth_step_to_aim2,
String_health_to_zero,
String_you_can_write_to_highscore,

String_empty_52,
String_empty_53,
String_empty_54, 
String_empty_55,
String_empty_56,
String_empty_57,

String_userinterface_1a,
String_userinterface_1b,
String_userinterface_2,
String_userinterface_3,
String_userinterface_4,
String_userinterface_5,

String_empty_58,
String_empty_59,
String_empty_60,
String_empty_61,

String_health_explanation,
String_healthregeneration_explanation,
String_armour_explanation,
String_strength_explanation,
String_critical_chance_explanation,
String_critical_damage_explanation,
String_luck_explanation,
String_breakingspeed_explanation,
String_speed_explanation,
String_mana_explanation,
String_manaregeneration_explanation,

String_empty_62,
String_empty_63,
String_empty_64,

String_inventoryhelp_explanation_1,
String_inventoryhelp_explanation_2,
String_inventoryhelp_explanation_3,
String_inventoryhelp_explanation_4,
String_inventoryhelp_explanation_5,
String_inventoryhelp_explanation_6,
String_inventoryhelp_explanation_actions,
String_inventoryhelp_left_mouse,
String_inventoryhelp_left_1,
String_inventoryhelp_left_2,
String_inventoryhelp_left_3,
String_inventoryhelp_left_4,
String_inventoryhelp_right_mouse,
String_inventoryhelp_right,

String_empty_65,
String_empty_66,

String_buildinghelp_1,
String_buildinghelp_2,
String_buildinghelp_3,
String_buildinghelp_4,
String_buildinghelp_5,
String_buildinghelp_6,
String_buildinghelp_7,

String_empty_67,
String_empty_68,
String_empty_69,

String_magichelp_1,
String_magichelp_2,
String_magichelp_3,
String_magichelp_4,
String_magichelp_5,
String_magichelp_6,
String_magichelp_7,

String_empty_70,
String_empty_71,
String_empty_72,
String_empty_73,
String_empty_74,
String_empty_75,
String_empty_76,
String_empty_77,
String_empty_78,
String_empty_79,
String_empty_80,
String_empty_81,
String_empty_82,

String_not_enough_materials,
String_no_place_in_inventory,
String_build_button,

String_empty_83,
String_empty_84,

String_buildinginfo_arcanusring,
String_buildinginfo_battleaxe,
String_buildinginfo_battlestone,
String_buildinginfo_beehouse,
String_buildinginfo_bricks,
String_buildinginfo_brickwall,
String_buildinginfo_candle,
String_buildinginfo_cauldron,
String_buildinginfo_chest,
String_buildinginfo_cupboard,
String_buildinginfo_diadochitarmour,
String_buildinginfo_door,
String_buildinginfo_dynamite,
String_buildinginfo_furnance,
String_buildinginfo_glue,
String_buildinginfo_ironarmour,
String_buildinginfo_ironhelmet,
String_buildinginfo_ironring,
String_buildinginfo_irontrousers,
String_buildinginfo_ladder,
String_buildinginfo_lantern,
String_buildinginfo_leatherarmour,
String_buildinginfo_leatherhelmet,
String_buildinginfo_marblewall,
String_buildinginfo_pickaxe,
String_buildinginfo_sawdust,
String_buildinginfo_stonewall,
String_buildinginfo_sword,
String_buildinginfo_table,
String_buildinginfo_torch,
String_buildinginfo_woodstaff,
String_buildinginfo_woodwall,

String_cooking_button = 900,
String_bread_info = 901,
String_mead_info = 902,
String_radishsoup_info = 903,
String_slimepudding_info = 904,

String_dirt = 1000,
String_stone = 1001,
String_coalblock = 1002,
String_ironblock = 1003,
String_goldblock = 1004,
String_arcanusblock = 1005,
String_marble = 1006,
String_sulfurblock = 1007,
String_salpeterblock = 1008,
String_wood = 1009,
String_treetrunk = 1010,
String_treecrown = 1011,
String_furnance = 1012,
String_cupboard = 1013,
String_door = 1014,
String_chest = 1015,
String_table = 1016,
String_lantern = 1017,
String_beehouse = 1018,
String_torch = 1019,
String_cauldron = 1020,
String_clover = 1021,
String_radish = 1022,
String_mushroom = 1023,
String_stalagtit = 1024,
String_rubbish = 1025,
String_bricks = 1026,
String_princesscage = 1027,
String_bedrock = 1028,
String_beehive = 1029,
String_ladder = 1030,
String_metalbars = 1031,
String_stonewall = 1032,
String_woodwall = 1033,
String_marblewall = 1034,
String_brickwall = 1035,
String_coal = 1036,
String_woodstaff = 1037,
String_ironore = 1038,
String_iron = 1039,
String_goldore = 1040,
String_gold = 1041,
String_glue = 1042,
String_arcanus = 1043,
String_slime = 1044,
String_recipe = 1045,
String_wax = 1046,
String_cookingbook = 1047,
String_sawdust = 1048,
String_diadochit = 1049,
String_dynamite = 1050,
String_sulfur = 1051,
String_salpeter = 1052,
String_leather = 1053,
String_bone = 1054,
String_key = 1055,
String_honey = 1056,
String_mead = 1057,
String_slimepudding = 1058,
String_radishsoup = 1059,
String_bread = 1060,
String_pickaxe = 1061,
String_sword = 1062,
String_battleaxe = 1063,
String_battlestone = 1064,
String_goblindagger = 1065,
String_ironhelmet = 1066,
String_ironarmour = 1067,
String_irontrousers = 1068,
String_ironring = 1069,
String_arcanusring = 1070,
String_magichat = 1071,
String_candle = 1072,
String_diadochitarmour = 1073,
String_leatherarmour = 1074,
String_leatherhelmet = 1075,
String_veryrarering = 1076,
String_magicpoint = 1077,
String_skull_on_spear = 1078,

String_level = 3000,
String_language = 3001,
String_english = 3002,
String_german = 3003,

String_tutorial_aim = 5000,
String_tutorial_walking = 5001,
String_tutorial_jumping = 5002,
String_tutorial_breaking_a_jump = 5003,
String_tutorial_breaking = 5004,
String_tutorial_picking_up_items = 5005,
String_tutorial_get_dirt = 5006,
String_tutorial_open_inventory = 5007,
String_tutorial_inv_move_item = 5008,
String_tutorial_inv_divide_item = 5009,
String_tutorial_inv_quest_divide = 5010,
String_tutorial_lets_go = 5011,
};